DROP TABLE PEDIDO_ARTICULOSPEDIDO;
DROP TABLE ARTICULOSPEDIDO;
DROP TABLE PEDIDO;
DROP TABLE REMITO;
DROP TABLE FACTURA;
-- DROP TABLE CLIENTE_DOMICILIOENTREGA;
-- DROP TABLE DOMICILIOENTREGA;
-- DROP TABLE LOCALIDAD;
-- DROP TABLE PROVINCIA;
-- DROP TABLE PAIS;
-- DROP TABLE CLIENTE;
-- DROP TABLE ARTICULO;

UPDATE ARTICULO SET STOCK = 65 WHERE CODIGO = '1000';
UPDATE ARTICULO SET STOCK = 750 WHERE CODIGO = '1001';
UPDATE ARTICULO SET STOCK = 1522 WHERE CODIGO = '2000';
UPDATE ARTICULO SET STOCK = 35 WHERE CODIGO = '3000';
UPDATE ARTICULO SET STOCK = 100 WHERE CODIGO = '3001';
UPDATE ARTICULO SET STOCK = 4 WHERE CODIGO = '4000';
UPDATE ARTICULO SET STOCK = 100 WHERE CODIGO = '5000';
UPDATE ARTICULO SET STOCK = 4 WHERE CODIGO = '6000';


--SECUENCIA PARA EJECUTAR ANTES DE CADA TEST
--ant compile
--ant stage -Dstage stage2.sql
--ant redeploy

